<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<NoStdLib>True</NoStdLib>
		<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
		<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants);UEFI</DefineConstants>		
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);UEFI</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
		<Folder Include="System\Collections\" />
		<Folder Include="System\Linq\" />
		<Folder Include="System\Threading\" />
		<Folder Include="System\Threading\Tasks\" />
		<Folder Include="System\Text\" />
	</ItemGroup>

</Project>
